// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"task-manager-api/internal/biz"
	"task-manager-api/internal/conf"
	"task-manager-api/internal/data"
	"task-manager-api/internal/server"
	"task-manager-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	taskRepo := data.NewTaskRepo(dataData)
	taskUsecase := biz.NewTaskUsecase(taskRepo)
	taskService := service.NewTaskService(taskUsecase)
	grpcServer := server.NewGRPCServer(confServer, taskService)
	httpServer := server.NewHTTPServer(confServer, taskService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
